### PR TITLE
feat: support taiko protocol&t8ntool in reth

### PR DESCRIPTION
**Pull request by johntaiko**
# Taiko portocol & t8ntool

## TODOs

- [ ] t8n: js tracer
- [x] t8n: precheck the input.env
- [x] t8n: prehandle the input.txs

## Taiko protocol in node

https://github.com/ethereum/go-ethereum/compare/master...taikoxyz:taiko-geth:taiko

- [x] taiko: genesis block
- [x] taiko: anchor precheck
- [x] taiko: store anchor information in db
- [ ] taiko: additional batch APIs for raiko

### CODE REVIEW

**Comment by petarvujovic98** [comment]
@johntaiko What are you taking on currently? I want to jump on something so that we are not doing duplicate work

**Comment by pbeza** [comment]
@johntaiko @petarvujovic98 I have some lame questions about the tasks on the TODO list, as I'm not clear on the context or reasons for these specific items:

- What is the difference between Hive and t8ntool? Is the latter a subset of the former? Why is it necessary now if it wasn't for `taiko-mono`? Any specific reason?
- Are we moving from the `taiko-mono` (a fork of `geth`) to the `reth` fork? What is the reasoning behind this change? Where can I find the `reth` fork?

**Comment by johntaiko** [comment]
> * What is the difference between Hive and t8ntool? Is the latter a subset of the former? Why is it necessary now if it wasn't for `taiko-mono`? Any specific reason?

Hive is an e2e framework, you can consider t8ntool as a scaffold for unit tests.
Because we need to use t8ntool to test the specs in https://github.com/ethereum/tests just like what geth did

> * Are we moving from the `taiko-mono` (a fork of `geth`) to the `reth` fork? What is the reasoning behind this change? Where can I find the `reth` fork?

I think we will implement BBR in reth, and will share the details between raiko and reth.

**Comment by petarvujovic98** [comment]
@johntaiko Could you help me understand what should go in this part of the block building process for Taiko https://github.com/taikoxyz/reth/blob/ab178d6d61c0237bcceaa22edef54c958e48a634/crates/payload/taiko/src/builder.rs#L362-L374

**Comment by johntaiko** [comment]
> @johntaiko Could you help me understand what should go in this part of the block building process for Taiko
> 
> https://github.com/taikoxyz/reth/blob/ab178d6d61c0237bcceaa22edef54c958e48a634/crates/payload/taiko/src/builder.rs#L362-L374

You should use `receipts_root_slow` instead of `optimism_receipts_root_slow`. This part of code is used to calculate the root state of the current executed block.

But I think it's really complex to understand their abstraction, you can see my code in t8n, it's intuitive.
https://github.com/taikoxyz/reth/blob/955f5e9b97ddbe2f953d295cd98e8457d6e8cda1/bin/reth/src/commands/t8n/mod.rs#L508

**Comment by johntaiko** [comment]
> Just to confirm here, Taiko doesn't change this process compared to regular Eth then?

You only need to be concerned about the impact of the anchor.

**Comment by petarvujovic98** [comment]
@johntaiko I might need a bit help understanding how to implement [TxPoolContent](https://github.com/taikoxyz/taiko-geth/blob/8c7e9ffc4714e692af4231db9bd6b9969fd09a1b/eth/taiko_api_backend.go#L64) into Reth

**Comment by petarvujovic98** [comment]
@johntaiko We can now compile `taiko-reth` using:
```shell
cargo build -F taiko
```
and run `taiko-reth` using something like
```shell
./target/debug/taiko-reth node
```
but we need to test if the node actually had correct behavior. How can I run some tests to check for expected behavior compared to `taiko-geth`?

**Pull request closed without merging**
